### ISSUE TITLE
Loading & 401

### ISSUE THREAD

**Issue by ImJustLucas** [ImJustLucas/RiiWARD#28]
Créer des composant de loading et de page 401 pour une meilleure ui

**Comment by Kenny4297** [comment]
Bonjour @ImJustLucas, je pense pouvoir aider avec ce problème. Pourriez-vous m'attribuer cette tâche ?

**Comment by ImJustLucas** [comment]
Hello @Kenny4297 
Avac plaisir, les composants sont a placer dans le composant `RequireAuth.tsx`, a la racine du dossier components
je t'ai créé une branche dédié pour cette issue !
